# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service_study.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='absent', max_length=10)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('fine_pay', models.BooleanField(default=False)),
                ('fine_rate', models.IntegerField(default=0)),
                ('fine_reason', models.TextField()),
                ('hash_value', models.CharField(default=service_study.models._generate_hash, max_length=8, unique=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.Study')),
            ],
        ),
    ]
