# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0002_auto_20171015_1818'),
        ('service_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.Study')),
            ],
        ),
    ]
