# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='absent', max_length=10),
        ),
    ]
