# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0004_remove_studyuser_fine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_study', '0003_auto_20171007_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('fine_pay', models.BooleanField(default=False)),
                ('fine_rate', models.IntegerField(default=0)),
                ('fine_reason', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
