# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import service_study.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_study', '0004_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='hash_value',
            field=models.CharField(default=service_study.models._generate_hash, max_length=8, unique=True),
        ),
    ]
