# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import service_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='url',
            field=models.SlugField(default=service_main.models._generate_url, unique=True),
        ),
    ]
