# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='user_info',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
