# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0002_auto_20171003_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrequest',
            name='user_info',
        ),
    ]
