# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0002_auto_20170924_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
