# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0003_remove_studyrequest_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyuser',
            name='fine',
        ),
    ]
