# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Secret', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
