# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Secret', max_length=16),
        ),
    ]
